# Generated by Django 5.2.6 on 2025-10-07 18:42

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
