# Generated by Django 5.2.6 on 2025-10-07 18:42

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_tag_note_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
